package net.okdi.api.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ShopBroadcastInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long broadcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String senderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String senderPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long senderTownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String senderTownName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String senderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal senderLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.sender_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal senderLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String addresseeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String addresseePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long addresseeTownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String addresseeTownName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String addresseeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal addresseeLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.addressee_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal addresseeLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.trade_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal tradeDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.shop_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.shop_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String shopPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.service_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date serviceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.trade_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String tradeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Short productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.collection_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal collectionMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.freight_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal freightMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.total_amount
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.broadcast_status
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Short broadcastStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.single_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date singleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.take_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date takeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.finish_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.cancel_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.member_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private BigDecimal memberDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_info.modity_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date modityTime;
    
    
 
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.broadcast_id
     *
     * @return the value of shop_broadcast_info.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getBroadcastId() {
        return broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.broadcast_id
     *
     * @param broadcastId the value for shop_broadcast_info.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setBroadcastId(Long broadcastId) {
        this.broadcastId = broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_name
     *
     * @return the value of shop_broadcast_info.sender_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_name
     *
     * @param senderName the value for shop_broadcast_info.sender_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_phone
     *
     * @return the value of shop_broadcast_info.sender_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getSenderPhone() {
        return senderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_phone
     *
     * @param senderPhone the value for shop_broadcast_info.sender_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_town_id
     *
     * @return the value of shop_broadcast_info.sender_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getSenderTownId() {
        return senderTownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_town_id
     *
     * @param senderTownId the value for shop_broadcast_info.sender_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderTownId(Long senderTownId) {
        this.senderTownId = senderTownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_town_name
     *
     * @return the value of shop_broadcast_info.sender_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getSenderTownName() {
        return senderTownName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_town_name
     *
     * @param senderTownName the value for shop_broadcast_info.sender_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderTownName(String senderTownName) {
        this.senderTownName = senderTownName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_address
     *
     * @return the value of shop_broadcast_info.sender_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_address
     *
     * @param senderAddress the value for shop_broadcast_info.sender_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_longitude
     *
     * @return the value of shop_broadcast_info.sender_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getSenderLongitude() {
        return senderLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_longitude
     *
     * @param senderLongitude the value for shop_broadcast_info.sender_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderLongitude(BigDecimal senderLongitude) {
        this.senderLongitude = senderLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.sender_latitude
     *
     * @return the value of shop_broadcast_info.sender_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getSenderLatitude() {
        return senderLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.sender_latitude
     *
     * @param senderLatitude the value for shop_broadcast_info.sender_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSenderLatitude(BigDecimal senderLatitude) {
        this.senderLatitude = senderLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_name
     *
     * @return the value of shop_broadcast_info.addressee_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getAddresseeName() {
        return addresseeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_name
     *
     * @param addresseeName the value for shop_broadcast_info.addressee_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeName(String addresseeName) {
        this.addresseeName = addresseeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_phone
     *
     * @return the value of shop_broadcast_info.addressee_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getAddresseePhone() {
        return addresseePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_phone
     *
     * @param addresseePhone the value for shop_broadcast_info.addressee_phone
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseePhone(String addresseePhone) {
        this.addresseePhone = addresseePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_town_id
     *
     * @return the value of shop_broadcast_info.addressee_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getAddresseeTownId() {
        return addresseeTownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_town_id
     *
     * @param addresseeTownId the value for shop_broadcast_info.addressee_town_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeTownId(Long addresseeTownId) {
        this.addresseeTownId = addresseeTownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_town_name
     *
     * @return the value of shop_broadcast_info.addressee_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getAddresseeTownName() {
        return addresseeTownName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_town_name
     *
     * @param addresseeTownName the value for shop_broadcast_info.addressee_town_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeTownName(String addresseeTownName) {
        this.addresseeTownName = addresseeTownName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_address
     *
     * @return the value of shop_broadcast_info.addressee_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getAddresseeAddress() {
        return addresseeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_address
     *
     * @param addresseeAddress the value for shop_broadcast_info.addressee_address
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeAddress(String addresseeAddress) {
        this.addresseeAddress = addresseeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_longitude
     *
     * @return the value of shop_broadcast_info.addressee_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getAddresseeLongitude() {
        return addresseeLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_longitude
     *
     * @param addresseeLongitude the value for shop_broadcast_info.addressee_longitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeLongitude(BigDecimal addresseeLongitude) {
        this.addresseeLongitude = addresseeLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.addressee_latitude
     *
     * @return the value of shop_broadcast_info.addressee_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getAddresseeLatitude() {
        return addresseeLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.addressee_latitude
     *
     * @param addresseeLatitude the value for shop_broadcast_info.addressee_latitude
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setAddresseeLatitude(BigDecimal addresseeLatitude) {
        this.addresseeLatitude = addresseeLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.trade_distance
     *
     * @return the value of shop_broadcast_info.trade_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getTradeDistance() {
        return tradeDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.trade_distance
     *
     * @param tradeDistance the value for shop_broadcast_info.trade_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setTradeDistance(BigDecimal tradeDistance) {
        this.tradeDistance = tradeDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.shop_name
     *
     * @return the value of shop_broadcast_info.shop_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.shop_name
     *
     * @param shopName the value for shop_broadcast_info.shop_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.service_time
     *
     * @return the value of shop_broadcast_info.service_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.service_time
     *
     * @param serviceTime the value for shop_broadcast_info.service_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setServiceTime(Date serviceTime) {
        this.serviceTime = serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.trade_num
     *
     * @return the value of shop_broadcast_info.trade_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getTradeNum() {
        return tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.trade_num
     *
     * @param tradeNum the value for shop_broadcast_info.trade_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setTradeNum(String tradeNum) {
        this.tradeNum = tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.product_num
     *
     * @return the value of shop_broadcast_info.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Short getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.product_num
     *
     * @param productNum the value for shop_broadcast_info.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setProductNum(Short productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.collection_money
     *
     * @return the value of shop_broadcast_info.collection_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getCollectionMoney() {
        return collectionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.collection_money
     *
     * @param collectionMoney the value for shop_broadcast_info.collection_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setCollectionMoney(BigDecimal collectionMoney) {
        this.collectionMoney = collectionMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.freight_money
     *
     * @return the value of shop_broadcast_info.freight_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getFreightMoney() {
        return freightMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.freight_money
     *
     * @param freightMoney the value for shop_broadcast_info.freight_money
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setFreightMoney(BigDecimal freightMoney) {
        this.freightMoney = freightMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.total_amount
     *
     * @return the value of shop_broadcast_info.total_amount
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.total_amount
     *
     * @param totalAmount the value for shop_broadcast_info.total_amount
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.broadcast_status
     *
     * @return the value of shop_broadcast_info.broadcast_status
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Short getBroadcastStatus() {
        return broadcastStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.broadcast_status
     *
     * @param broadcastStatus the value for shop_broadcast_info.broadcast_status
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setBroadcastStatus(Short broadcastStatus) {
        this.broadcastStatus = broadcastStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.single_time
     *
     * @return the value of shop_broadcast_info.single_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getSingleTime() {
        return singleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.single_time
     *
     * @param singleTime the value for shop_broadcast_info.single_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setSingleTime(Date singleTime) {
        this.singleTime = singleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.take_time
     *
     * @return the value of shop_broadcast_info.take_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.take_time
     *
     * @param takeTime the value for shop_broadcast_info.take_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setTakeTime(Date takeTime) {
        this.takeTime = takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.finish_time
     *
     * @return the value of shop_broadcast_info.finish_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.finish_time
     *
     * @param finishTime the value for shop_broadcast_info.finish_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.cancel_time
     *
     * @return the value of shop_broadcast_info.cancel_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.cancel_time
     *
     * @param cancelTime the value for shop_broadcast_info.cancel_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.member_id
     *
     * @return the value of shop_broadcast_info.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.member_id
     *
     * @param memberId the value for shop_broadcast_info.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.member_distance
     *
     * @return the value of shop_broadcast_info.member_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public BigDecimal getMemberDistance() {
        return memberDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.member_distance
     *
     * @param memberDistance the value for shop_broadcast_info.member_distance
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setMemberDistance(BigDecimal memberDistance) {
        this.memberDistance = memberDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.create_time
     *
     * @return the value of shop_broadcast_info.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.create_time
     *
     * @param createTime the value for shop_broadcast_info.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_info.modity_time
     *
     * @return the value of shop_broadcast_info.modity_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getModityTime() {
        return modityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_info.modity_time
     *
     * @param modityTime the value for shop_broadcast_info.modity_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setModityTime(Date modityTime) {
        this.modityTime = modityTime;
    }

	public String getShopPhone() {
		return shopPhone;
	}

	public void setShopPhone(String shopPhone) {
		this.shopPhone = shopPhone;
	}
    
}