package net.okdi.api.entity;

import java.util.Date;

public class BasExpressservice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.service_name
     *
     * @mbggenerated
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.service_desc
     *
     * @mbggenerated
     */
    private String serviceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.service_time
     *
     * @mbggenerated
     */
    private Short serviceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_expressservice.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.id
     *
     * @return the value of bas_expressservice.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.id
     *
     * @param id the value for bas_expressservice.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.service_name
     *
     * @return the value of bas_expressservice.service_name
     *
     * @mbggenerated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.service_name
     *
     * @param serviceName the value for bas_expressservice.service_name
     *
     * @mbggenerated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.service_desc
     *
     * @return the value of bas_expressservice.service_desc
     *
     * @mbggenerated
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.service_desc
     *
     * @param serviceDesc the value for bas_expressservice.service_desc
     *
     * @mbggenerated
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.service_time
     *
     * @return the value of bas_expressservice.service_time
     *
     * @mbggenerated
     */
    public Short getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.service_time
     *
     * @param serviceTime the value for bas_expressservice.service_time
     *
     * @mbggenerated
     */
    public void setServiceTime(Short serviceTime) {
        this.serviceTime = serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.create_time
     *
     * @return the value of bas_expressservice.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.create_time
     *
     * @param createTime the value for bas_expressservice.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_expressservice.create_user_id
     *
     * @return the value of bas_expressservice.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_expressservice.create_user_id
     *
     * @param createUserId the value for bas_expressservice.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }
}