package net.okdi.api.entity;

import java.util.Date;

public class MemberInvitationRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.relation_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.shop_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.member_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.member_phone
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private String memberPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.register_flag
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private Short registerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.create_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_invitation_relation.modity_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    private Date modityTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.relation_id
     *
     * @return the value of member_invitation_relation.relation_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.relation_id
     *
     * @param relationId the value for member_invitation_relation.relation_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.shop_id
     *
     * @return the value of member_invitation_relation.shop_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.shop_id
     *
     * @param shopId the value for member_invitation_relation.shop_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.member_id
     *
     * @return the value of member_invitation_relation.member_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.member_id
     *
     * @param memberId the value for member_invitation_relation.member_id
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.member_phone
     *
     * @return the value of member_invitation_relation.member_phone
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.member_phone
     *
     * @param memberPhone the value for member_invitation_relation.member_phone
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.register_flag
     *
     * @return the value of member_invitation_relation.register_flag
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public Short getRegisterFlag() {
        return registerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.register_flag
     *
     * @param registerFlag the value for member_invitation_relation.register_flag
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setRegisterFlag(Short registerFlag) {
        this.registerFlag = registerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.create_time
     *
     * @return the value of member_invitation_relation.create_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.create_time
     *
     * @param createTime the value for member_invitation_relation.create_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_invitation_relation.modity_time
     *
     * @return the value of member_invitation_relation.modity_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public Date getModityTime() {
        return modityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_invitation_relation.modity_time
     *
     * @param modityTime the value for member_invitation_relation.modity_time
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    public void setModityTime(Date modityTime) {
        this.modityTime = modityTime;
    }
}