package net.okdi.api.entity;

public class ShopTradeItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_item.id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_item.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long broadcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_item.product_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_item.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Integer productNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_item.id
     *
     * @return the value of shop_trade_item.id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_item.id
     *
     * @param id the value for shop_trade_item.id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_item.broadcast_id
     *
     * @return the value of shop_trade_item.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getBroadcastId() {
        return broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_item.broadcast_id
     *
     * @param broadcastId the value for shop_trade_item.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setBroadcastId(Long broadcastId) {
        this.broadcastId = broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_item.product_name
     *
     * @return the value of shop_trade_item.product_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_item.product_name
     *
     * @param productName the value for shop_trade_item.product_name
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_item.product_num
     *
     * @return the value of shop_trade_item.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_item.product_num
     *
     * @param productNum the value for shop_trade_item.product_num
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }
}