package net.okdi.api.entity;

import java.util.Date;

public class ShopBroadcastPushRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_push_relation.relation_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_push_relation.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long broadcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_push_relation.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_broadcast_push_relation.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_push_relation.relation_id
     *
     * @return the value of shop_broadcast_push_relation.relation_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_push_relation.relation_id
     *
     * @param relationId the value for shop_broadcast_push_relation.relation_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_push_relation.broadcast_id
     *
     * @return the value of shop_broadcast_push_relation.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getBroadcastId() {
        return broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_push_relation.broadcast_id
     *
     * @param broadcastId the value for shop_broadcast_push_relation.broadcast_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setBroadcastId(Long broadcastId) {
        this.broadcastId = broadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_push_relation.member_id
     *
     * @return the value of shop_broadcast_push_relation.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_push_relation.member_id
     *
     * @param memberId the value for shop_broadcast_push_relation.member_id
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_broadcast_push_relation.create_time
     *
     * @return the value of shop_broadcast_push_relation.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_broadcast_push_relation.create_time
     *
     * @param createTime the value for shop_broadcast_push_relation.create_time
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}