package net.okdi.mob.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BasOnlineMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.NET_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Long netId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.NET_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private String netName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.COMP_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Long compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.COMP_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.MEMBER_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.MEMBER_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.MEMBER_MOBILE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private String memberMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.LONGITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.LATITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.MODIFY_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.CREATE_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_online_member.MEMO
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    private String memo;

    private String memberUrl;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.ID
     *
     * @return the value of bas_online_member.ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.ID
     *
     * @param id the value for bas_online_member.ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.NET_ID
     *
     * @return the value of bas_online_member.NET_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Long getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.NET_ID
     *
     * @param netId the value for bas_online_member.NET_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setNetId(Long netId) {
        this.netId = netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.NET_NAME
     *
     * @return the value of bas_online_member.NET_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public String getNetName() {
        return netName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.NET_NAME
     *
     * @param netName the value for bas_online_member.NET_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setNetName(String netName) {
        this.netName = netName == null ? null : netName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.COMP_ID
     *
     * @return the value of bas_online_member.COMP_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.COMP_ID
     *
     * @param compId the value for bas_online_member.COMP_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.COMP_NAME
     *
     * @return the value of bas_online_member.COMP_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.COMP_NAME
     *
     * @param compName the value for bas_online_member.COMP_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.MEMBER_ID
     *
     * @return the value of bas_online_member.MEMBER_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.MEMBER_ID
     *
     * @param memberId the value for bas_online_member.MEMBER_ID
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.MEMBER_NAME
     *
     * @return the value of bas_online_member.MEMBER_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.MEMBER_NAME
     *
     * @param memberName the value for bas_online_member.MEMBER_NAME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.MEMBER_MOBILE
     *
     * @return the value of bas_online_member.MEMBER_MOBILE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public String getMemberMobile() {
        return memberMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.MEMBER_MOBILE
     *
     * @param memberMobile the value for bas_online_member.MEMBER_MOBILE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setMemberMobile(String memberMobile) {
        this.memberMobile = memberMobile == null ? null : memberMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.LONGITUDE
     *
     * @return the value of bas_online_member.LONGITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.LONGITUDE
     *
     * @param longitude the value for bas_online_member.LONGITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.LATITUDE
     *
     * @return the value of bas_online_member.LATITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.LATITUDE
     *
     * @param latitude the value for bas_online_member.LATITUDE
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.MODIFY_TIME
     *
     * @return the value of bas_online_member.MODIFY_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.MODIFY_TIME
     *
     * @param modifyTime the value for bas_online_member.MODIFY_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.CREATE_TIME
     *
     * @return the value of bas_online_member.CREATE_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.CREATE_TIME
     *
     * @param createTime the value for bas_online_member.CREATE_TIME
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_online_member.MEMO
     *
     * @return the value of bas_online_member.MEMO
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_online_member.MEMO
     *
     * @param memo the value for bas_online_member.MEMO
     *
     * @mbggenerated Tue Nov 25 11:50:10 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

	public String getMemberUrl() {
		return memberUrl;
	}

	public void setMemberUrl(String memberUrl) {
		this.memberUrl = memberUrl;
	}
    
}