package net.okdi.api.dao;

import java.util.List;

import net.okdi.api.entity.RobPushRelation;

public interface RobPushRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    int insert(RobPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    int insertSelective(RobPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    RobPushRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    int updateByPrimaryKeySelective(RobPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rob_push_relation
     *
     * @mbggenerated Wed Jun 17 13:05:37 CST 2015
     */
    int updateByPrimaryKey(RobPushRelation record);
    int batchRobPushRelation(List<RobPushRelation> robPushRelationList);
    List<Object> selectMemberIdsByBroadcastId(Long broadcastId);
}