package net.okdi.api.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import net.okdi.api.entity.SensitiveWord;

public interface SensitiveWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    int insert(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    int insertSelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    SensitiveWord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    int updateByPrimaryKeySelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    int updateByPrimaryKey(SensitiveWord record);
    /**
     * 根据类型查询敏感字表的数据
     * @param type 0:黑名单 1:白名单    查询的全部都是状态为0（0：启用，1：禁用）的数据
     * @return
     */
    List<String> selectByType(String type);
    
    /**
     * 判断是否重复
     */
    Integer selectBySensitiveWordAndType(@Param("sensitiveWord")String sensitiveWord);
	/**
	 * 添加关键字
	 */
	int insertSensitiveWord(SensitiveWord record);
	/**
	 * 删除关键字
	 */
	int deleteSensitiveWord(@Param("sensitiveWord")String sensitiveWord,@Param("type")String type);
	/**
	 * 模糊查询关键字
	 */
	List<String> likeSensitiveWord(@Param("sensitiveWord")String sensitiveWord,@Param("type")String type);
}