package net.okdi.api.dao;

import java.util.List;

import net.okdi.api.entity.ShopBroadcastPushRelation;
import net.okdi.api.entity.ShopTradeItem;

public interface ShopBroadcastPushRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int insert(ShopBroadcastPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int insertSelective(ShopBroadcastPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    ShopBroadcastPushRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int updateByPrimaryKeySelective(ShopBroadcastPushRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_broadcast_push_relation
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int updateByPrimaryKey(ShopBroadcastPushRelation record);
    //批量插入
    int insertList(List<ShopBroadcastPushRelation> list);
}