package net.okdi.api.entity;

public class ShopMemberPushSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_member_push_set.member_id
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_member_push_set.push_status
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    private Short pushStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_member_push_set.member_id
     *
     * @return the value of shop_member_push_set.member_id
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_member_push_set.member_id
     *
     * @param memberId the value for shop_member_push_set.member_id
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_member_push_set.push_status
     *
     * @return the value of shop_member_push_set.push_status
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    public Short getPushStatus() {
        return pushStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_member_push_set.push_status
     *
     * @param pushStatus the value for shop_member_push_set.push_status
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    public void setPushStatus(Short pushStatus) {
        this.pushStatus = pushStatus;
    }
}