package net.okdi.api.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import net.okdi.api.entity.ShopTradeItem;

public interface ShopTradeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int insert(ShopTradeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int insertSelective(ShopTradeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    ShopTradeItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int updateByPrimaryKeySelective(ShopTradeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_trade_item
     *
     * @mbggenerated Wed Jul 22 12:38:40 CST 2015
     */
    int updateByPrimaryKey(ShopTradeItem record);
    //批量插入
    int insertList(List<ShopTradeItem> list);
    //通过广播id查询商品信息
    List<Map> findShopTradeById(@Param("broadcastId")Long broadcastId); 
}