package net.okdi.api.dao;

import net.okdi.api.entity.MemberInvitationRelation;
import net.okdi.core.base.BaseDao;

public interface MemberInvitationRelationMapper  extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    int insert(MemberInvitationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    int insertSelective(MemberInvitationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    MemberInvitationRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    int updateByPrimaryKeySelective(MemberInvitationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_invitation_relation
     *
     * @mbggenerated Thu Jul 09 15:55:44 CST 2015
     */
    int updateregisterFlag(Long memberId);
    public MemberInvitationRelation getRelation(Long memberId);
}