package net.okdi.schedule.entity;

import java.sql.Timestamp;
import java.util.Date;

public class ParLogisticSearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.channel_no
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String channelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.channel_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.net_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Long netId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.net_code
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String netCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.exp_waybill_num
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String expWaybillNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.exp_type
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String expType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.trace_status
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String traceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.created_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.modified_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.appoint_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private Long appointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.rec_mobile
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String recMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.system_mark
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String systemMark;
    private Short pushMark;//是否需要推送的标识
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column par_logistic_search.trace_detail
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    private String traceDetail;

    public ParLogisticSearch(){}
    public ParLogisticSearch(  String netCode,
			String expWaybillNum, String traceStatus, Long channelId,
			String channelNo, String expType, Timestamp modifyTime,
			Timestamp createTime, String traceDetail, Integer charLength) {
		super();
		
		this.netCode = netCode;
		this.expWaybillNum = expWaybillNum;
		this.traceStatus = traceStatus;
		this.channelId = channelId;
		this.channelNo = channelNo;
		this.expType = expType;
		this.modifiedTime = modifyTime;
		this.createdTime = createTime;
		this.traceDetail = traceDetail;
	}
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.id
     *
     * @return the value of par_logistic_search.id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.id
     *
     * @param id the value for par_logistic_search.id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.channel_no
     *
     * @return the value of par_logistic_search.channel_no
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.channel_no
     *
     * @param channelNo the value for par_logistic_search.channel_no
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo == null ? null : channelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.channel_id
     *
     * @return the value of par_logistic_search.channel_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.channel_id
     *
     * @param channelId the value for par_logistic_search.channel_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.net_id
     *
     * @return the value of par_logistic_search.net_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Long getNetId() {
        return netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.net_id
     *
     * @param netId the value for par_logistic_search.net_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setNetId(Long netId) {
        this.netId = netId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.net_code
     *
     * @return the value of par_logistic_search.net_code
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getNetCode() {
        return netCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.net_code
     *
     * @param netCode the value for par_logistic_search.net_code
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setNetCode(String netCode) {
        this.netCode = netCode == null ? null : netCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.exp_waybill_num
     *
     * @return the value of par_logistic_search.exp_waybill_num
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getExpWaybillNum() {
        return expWaybillNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.exp_waybill_num
     *
     * @param expWaybillNum the value for par_logistic_search.exp_waybill_num
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setExpWaybillNum(String expWaybillNum) {
        this.expWaybillNum = expWaybillNum == null ? null : expWaybillNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.exp_type
     *
     * @return the value of par_logistic_search.exp_type
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getExpType() {
        return expType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.exp_type
     *
     * @param expType the value for par_logistic_search.exp_type
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setExpType(String expType) {
        this.expType = expType == null ? null : expType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.trace_status
     *
     * @return the value of par_logistic_search.trace_status
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getTraceStatus() {
        return traceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.trace_status
     *
     * @param traceStatus the value for par_logistic_search.trace_status
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setTraceStatus(String traceStatus) {
        this.traceStatus = traceStatus == null ? null : traceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.created_time
     *
     * @return the value of par_logistic_search.created_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.created_time
     *
     * @param createdTime the value for par_logistic_search.created_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.modified_time
     *
     * @return the value of par_logistic_search.modified_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.modified_time
     *
     * @param modifiedTime the value for par_logistic_search.modified_time
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.appoint_id
     *
     * @return the value of par_logistic_search.appoint_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public Long getAppointId() {
        return appointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.appoint_id
     *
     * @param appointId the value for par_logistic_search.appoint_id
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setAppointId(Long appointId) {
        this.appointId = appointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.rec_mobile
     *
     * @return the value of par_logistic_search.rec_mobile
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getRecMobile() {
        return recMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.rec_mobile
     *
     * @param recMobile the value for par_logistic_search.rec_mobile
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setRecMobile(String recMobile) {
        this.recMobile = recMobile == null ? null : recMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.system_mark
     *
     * @return the value of par_logistic_search.system_mark
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getSystemMark() {
        return systemMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.system_mark
     *
     * @param systemMark the value for par_logistic_search.system_mark
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setSystemMark(String systemMark) {
        this.systemMark = systemMark == null ? null : systemMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column par_logistic_search.trace_detail
     *
     * @return the value of par_logistic_search.trace_detail
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public String getTraceDetail() {
        return traceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column par_logistic_search.trace_detail
     *
     * @param traceDetail the value for par_logistic_search.trace_detail
     *
     * @mbggenerated Tue Nov 11 13:53:04 CST 2014
     */
    public void setTraceDetail(String traceDetail) {
        this.traceDetail = traceDetail == null ? null : traceDetail.trim();
    }
	public Short getPushMark() {
		return pushMark;
	}
	public void setPushMark(Short pushMark) {
		this.pushMark = pushMark;
	}
    
}