package net.okdi.api.dao;

import net.okdi.api.entity.ShopMemberPushSet;

public interface ShopMemberPushSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    int insert(ShopMemberPushSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    int insertSelective(ShopMemberPushSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    ShopMemberPushSet selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    int updateByPrimaryKeySelective(ShopMemberPushSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_member_push_set
     *
     * @mbggenerated Thu Jul 23 16:49:26 CST 2015
     */
    int updateByPrimaryKey(ShopMemberPushSet record);
}