package net.okdi.api.entity;

public class BasClientPushJurisdiction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_client_push_jurisdiction.member_id
     *
     * @mbggenerated Wed Oct 29 19:27:28 CST 2014
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_client_push_jurisdiction.phone_client_push_switch
     *
     * @mbggenerated Wed Oct 29 19:27:28 CST 2014
     */
    private String phoneClientPushSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_client_push_jurisdiction.pc_client_push_switch
     *
     * @mbggenerated Wed Oct 29 19:27:28 CST 2014
     */
    private String pcClientPushSwitch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_client_push_jurisdiction.member_id
     *
     * @return the value of bas_client_push_jurisdiction.member_id
     *
     * @mbggenerated Wed Oct 29 19:27:28 CST 2014
     */
    public Long getMemberId() {
        return memberId;
    }

    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
    public String getPhoneClientPushSwitch() {
        return phoneClientPushSwitch;
    }
    public void setPhoneClientPushSwitch(String phoneClientPushSwitch) {
        this.phoneClientPushSwitch = phoneClientPushSwitch == null ? null : phoneClientPushSwitch.trim();
    }
    public String getPcClientPushSwitch() {
        return pcClientPushSwitch;
    }
    public void setPcClientPushSwitch(String pcClientPushSwitch) {
        this.pcClientPushSwitch = pcClientPushSwitch == null ? null : pcClientPushSwitch.trim();
    }
}