package net.okdi.api.entity;

public class SensitiveWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.id
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    private String sensitiveWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.type
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.state
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.id
     *
     * @return the value of sensitive_word.id
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.id
     *
     * @param id the value for sensitive_word.id
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Sensitive_word
     *
     * @return the value of sensitive_word.Sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public String getSensitiveWord() {
        return sensitiveWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Sensitive_word
     *
     * @param sensitiveWord the value for sensitive_word.Sensitive_word
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public void setSensitiveWord(String sensitiveWord) {
        this.sensitiveWord = sensitiveWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.type
     *
     * @return the value of sensitive_word.type
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.type
     *
     * @param type the value for sensitive_word.type
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.state
     *
     * @return the value of sensitive_word.state
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.state
     *
     * @param state the value for sensitive_word.state
     *
     * @mbggenerated Wed Aug 19 18:25:19 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }
}